-- Auto-generated from laminas/*.png
-- Run this after db/schema.sql.

insert into public.paises (id, nombre, flag, initials) values
  (1, 'Chile', '🇨🇱', 'CL'),
  (2, 'Argentina', '🇦🇷', 'AR'),
  (3, 'Colombia', '🇨🇴', 'CO'),
  (4, 'México', '🇲🇽', 'MX')
on conflict (id) do update set
  nombre = excluded.nombre,
  flag = excluded.flag,
  initials = excluded.initials;

insert into public.usuarios (id, name, role, pais_id, login_name, login_password, lamina_path) values
  (1, 'Abrahamzick Orozco', 'CEO', 1, 'Abrahamzick Orozco', 'Abrahamzick Orozco', 'laminas/Abrahamzick Orozco.png'),
  (2, 'Adrián Sepúlveda', 'Producto', 2, 'Adrián Sepúlveda', 'Adrián Sepúlveda', 'laminas/Adrián Sepúlveda.png'),
  (3, 'Adriana Celis', 'Desarrollo', 3, 'Adriana Celis', 'Adriana Celis', 'laminas/Adriana Celis.png'),
  (4, 'Alberto Bachler', 'CS', 4, 'Alberto Bachler', 'Alberto Bachler', 'laminas/Alberto Bachler.png'),
  (5, 'Aldo Ayala', 'Desarrollo', 1, 'Aldo Ayala', 'Aldo Ayala', 'laminas/Aldo Ayala.png'),
  (6, 'Alejandro Albertz', 'Diseño', 2, 'Alejandro Albertz', 'Alejandro Albertz', 'laminas/Alejandro Albertz.png'),
  (7, 'Alejandro González', 'Ventas', 3, 'Alejandro González', 'Alejandro González', 'laminas/Alejandro González.png'),
  (8, 'Alexis Bustamante', 'CS', 4, 'Alexis Bustamante', 'Alexis Bustamante', 'laminas/Alexis Bustamante.png'),
  (9, 'Álvaro Bueno', 'Desarrollo', 1, 'Álvaro Bueno', 'Álvaro Bueno', 'laminas/Álvaro Bueno.png'),
  (10, 'Andrés Ordoñez', 'Marketing', 2, 'Andrés Ordoñez', 'Andrés Ordoñez', 'laminas/Andrés Ordoñez.png'),
  (11, 'Andrés Osorio', 'Operaciones', 3, 'Andrés Osorio', 'Andrés Osorio', 'laminas/Andrés Osorio.png'),
  (12, 'Andrés Quiero', 'Finanzas', 4, 'Andrés Quiero', 'Andrés Quiero', 'laminas/Andrés Quiero.png'),
  (13, 'Andrés Tolosa', 'Desarrollo', 1, 'Andrés Tolosa', 'Andrés Tolosa', 'laminas/Andrés Tolosa.png'),
  (14, 'Ángel Castillo', 'RRHH', 2, 'Ángel Castillo', 'Ángel Castillo', 'laminas/Ángel Castillo.png'),
  (15, 'Ángela Sierra', 'Ventas', 3, 'Ángela Sierra', 'Ángela Sierra', 'laminas/Ángela Sierra.png'),
  (16, 'Angie Callejas', 'CS', 4, 'Angie Callejas', 'Angie Callejas', 'laminas/Angie Callejas.png'),
  (17, 'Ariadna Flores', 'Desarrollo', 1, 'Ariadna Flores', 'Ariadna Flores', 'laminas/Ariadna Flores.png'),
  (18, 'Ariel Gringaus', 'Producto', 2, 'Ariel Gringaus', 'Ariel Gringaus', 'laminas/Ariel Gringaus.png'),
  (19, 'Ariel Rojas', 'Infraestructura', 3, 'Ariel Rojas', 'Ariel Rojas', 'laminas/Ariel Rojas.png'),
  (20, 'Arnoldo Chazeau', 'Diseño', 4, 'Arnoldo Chazeau', 'Arnoldo Chazeau', 'laminas/Arnoldo Chazeau.png'),
  (21, 'Arturo Rincón', 'Desarrollo', 1, 'Arturo Rincón', 'Arturo Rincón', 'laminas/Arturo Rincón.png'),
  (22, 'Ashly Flores', 'CS', 2, 'Ashly Flores', 'Ashly Flores', 'laminas/Ashly Flores.png'),
  (23, 'Aymara Martínez', 'Ventas', 3, 'Aymara Martínez', 'Aymara Martínez', 'laminas/Aymara Martínez.png'),
  (24, 'Bastián Vallejos', 'Marketing', 4, 'Bastián Vallejos', 'Bastián Vallejos', 'laminas/Bastián Vallejos.png'),
  (25, 'Belén Ávila', 'CEO', 1, 'Belén Ávila', 'Belén Ávila', 'laminas/Belén Ávila.png'),
  (26, 'Brenda Aquino', 'Producto', 2, 'Brenda Aquino', 'Brenda Aquino', 'laminas/Brenda Aquino.png'),
  (27, 'Camila Casanova', 'Desarrollo', 3, 'Camila Casanova', 'Camila Casanova', 'laminas/Camila Casanova.png'),
  (28, 'Carlos Rodríguez', 'CS', 4, 'Carlos Rodríguez', 'Carlos Rodríguez', 'laminas/Carlos Rodríguez.png'),
  (29, 'Carlos Vega', 'Desarrollo', 1, 'Carlos Vega', 'Carlos Vega', 'laminas/Carlos Vega.png'),
  (30, 'Carolina Araya', 'Diseño', 2, 'Carolina Araya', 'Carolina Araya', 'laminas/Carolina Araya.png'),
  (31, 'Catalina Fuentealba', 'Ventas', 3, 'Catalina Fuentealba', 'Catalina Fuentealba', 'laminas/Catalina Fuentealba.png'),
  (32, 'Catalina Mantilla', 'CS', 4, 'Catalina Mantilla', 'Catalina Mantilla', 'laminas/Catalina Mantilla.png'),
  (33, 'Cesar Matheus', 'Desarrollo', 1, 'Cesar Matheus', 'Cesar Matheus', 'laminas/Cesar Matheus.png'),
  (34, 'Cristian Henríquez', 'Marketing', 2, 'Cristian Henríquez', 'Cristian Henríquez', 'laminas/Cristian Henríquez.png'),
  (35, 'Cristian Noguera', 'Operaciones', 3, 'Cristian Noguera', 'Cristian Noguera', 'laminas/Cristian Noguera.png'),
  (36, 'Cristian Zapata', 'Finanzas', 4, 'Cristian Zapata', 'Cristian Zapata', 'laminas/Cristian Zapata.png'),
  (37, 'Cristina Molina', 'Desarrollo', 1, 'Cristina Molina', 'Cristina Molina', 'laminas/Cristina Molina.png'),
  (38, 'Cynthia Marchant', 'RRHH', 2, 'Cynthia Marchant', 'Cynthia Marchant', 'laminas/Cynthia Marchant.png'),
  (39, 'Daniel Medina', 'Ventas', 3, 'Daniel Medina', 'Daniel Medina', 'laminas/Daniel Medina.png'),
  (40, 'Daniela Parra', 'CS', 4, 'Daniela Parra', 'Daniela Parra', 'laminas/Daniela Parra.png'),
  (41, 'David Barreda', 'Desarrollo', 1, 'David Barreda', 'David Barreda', 'laminas/David Barreda.png'),
  (42, 'David Guarín', 'Producto', 2, 'David Guarín', 'David Guarín', 'laminas/David Guarín.png'),
  (43, 'Derly Flórez', 'Infraestructura', 3, 'Derly Flórez', 'Derly Flórez', 'laminas/Derly Flórez.png'),
  (44, 'Diana Sandoval', 'Diseño', 4, 'Diana Sandoval', 'Diana Sandoval', 'laminas/Diana Sandoval.png'),
  (45, 'Edward Henao', 'Desarrollo', 1, 'Edward Henao', 'Edward Henao', 'laminas/Edward Henao.png'),
  (46, 'Esteban Aguirre', 'CS', 2, 'Esteban Aguirre', 'Esteban Aguirre', 'laminas/Esteban Aguirre.png'),
  (47, 'Evelyn Espejo', 'Ventas', 3, 'Evelyn Espejo', 'Evelyn Espejo', 'laminas/Evelyn Espejo.png'),
  (48, 'Ezequiel Balasch', 'Marketing', 4, 'Ezequiel Balasch', 'Ezequiel Balasch', 'laminas/Ezequiel Balasch.png'),
  (49, 'Felipe Miranda', 'CEO', 1, 'Felipe Miranda', 'Felipe Miranda', 'laminas/Felipe Miranda.png'),
  (50, 'Felipe Weiss', 'Producto', 2, 'Felipe Weiss', 'Felipe Weiss', 'laminas/Felipe Weiss.png'),
  (51, 'Fernanda Florez', 'Desarrollo', 3, 'Fernanda Florez', 'Fernanda Florez', 'laminas/Fernanda Florez.png'),
  (52, 'Francisca Soto', 'CS', 4, 'Francisca Soto', 'Francisca Soto', 'laminas/Francisca Soto.png'),
  (53, 'Gabriela Jugo', 'Desarrollo', 1, 'Gabriela Jugo', 'Gabriela Jugo', 'laminas/Gabriela Jugo.png'),
  (54, 'Genito Andrade', 'Diseño', 2, 'Genito Andrade', 'Genito Andrade', 'laminas/Genito Andrade.png'),
  (55, 'Gerardo Barragán', 'Ventas', 3, 'Gerardo Barragán', 'Gerardo Barragán', 'laminas/Gerardo Barragán.png'),
  (56, 'Gonzalo Bertomeu', 'CS', 4, 'Gonzalo Bertomeu', 'Gonzalo Bertomeu', 'laminas/Gonzalo Bertomeu.png'),
  (57, 'Gonzalo de la Jara', 'Desarrollo', 1, 'Gonzalo de la Jara', 'Gonzalo de la Jara', 'laminas/Gonzalo de la Jara.png'),
  (58, 'Gonzalo López', 'Marketing', 2, 'Gonzalo López', 'Gonzalo López', 'laminas/Gonzalo López.png'),
  (59, 'Héctor Rojo', 'Operaciones', 3, 'Héctor Rojo', 'Héctor Rojo', 'laminas/Héctor Rojo.png'),
  (60, 'Ignacio Portilla', 'Finanzas', 4, 'Ignacio Portilla', 'Ignacio Portilla', 'laminas/Ignacio Portilla.png'),
  (61, 'Israel Flores', 'Desarrollo', 1, 'Israel Flores', 'Israel Flores', 'laminas/Israel Flores.png'),
  (62, 'Jaime Herreros', 'RRHH', 2, 'Jaime Herreros', 'Jaime Herreros', 'laminas/Jaime Herreros.png'),
  (63, 'Javier Espinoza', 'Ventas', 3, 'Javier Espinoza', 'Javier Espinoza', 'laminas/Javier Espinoza.png'),
  (64, 'Javier Fonseca', 'CS', 4, 'Javier Fonseca', 'Javier Fonseca', 'laminas/Javier Fonseca.png'),
  (65, 'Javiera Huentemil', 'Desarrollo', 1, 'Javiera Huentemil', 'Javiera Huentemil', 'laminas/Javiera Huentemil.png'),
  (66, 'Jeison Jiménez', 'Producto', 2, 'Jeison Jiménez', 'Jeison Jiménez', 'laminas/Jeison Jiménez.png'),
  (67, 'Jennifer Luengas', 'Infraestructura', 3, 'Jennifer Luengas', 'Jennifer Luengas', 'laminas/Jennifer Luengas.png'),
  (68, 'Jesús Osorio', 'Diseño', 4, 'Jesús Osorio', 'Jesús Osorio', 'laminas/Jesús Osorio.png'),
  (69, 'Johan Casanova', 'Desarrollo', 1, 'Johan Casanova', 'Johan Casanova', 'laminas/Johan Casanova.png'),
  (70, 'Johan Rosas', 'CS', 2, 'Johan Rosas', 'Johan Rosas', 'laminas/Johan Rosas.png'),
  (71, 'Jonathan Sepúlveda', 'Ventas', 3, 'Jonathan Sepúlveda', 'Jonathan Sepúlveda', 'laminas/Jonathan Sepúlveda.png'),
  (72, 'Jorge Reynoso', 'Marketing', 4, 'Jorge Reynoso', 'Jorge Reynoso', 'laminas/Jorge Reynoso.png'),
  (73, 'José Manuel Barros', 'CEO', 1, 'José Manuel Barros', 'José Manuel Barros', 'laminas/José Manuel Barros.png'),
  (74, 'José Matus', 'Producto', 2, 'José Matus', 'José Matus', 'laminas/José Matus.png'),
  (75, 'Jose Miguel Moreno', 'Desarrollo', 3, 'Jose Miguel Moreno', 'Jose Miguel Moreno', 'laminas/Jose Miguel Moreno.png'),
  (76, 'José Romero', 'CS', 4, 'José Romero', 'José Romero', 'laminas/José Romero.png'),
  (77, 'Juan David Loaiza', 'Desarrollo', 1, 'Juan David Loaiza', 'Juan David Loaiza', 'laminas/Juan David Loaiza.png'),
  (78, 'Juan Ignacio Castro', 'Diseño', 2, 'Juan Ignacio Castro', 'Juan Ignacio Castro', 'laminas/Juan Ignacio Castro.png'),
  (79, 'Juan Manuel Zúñiga', 'Ventas', 3, 'Juan Manuel Zúñiga', 'Juan Manuel Zúñiga', 'laminas/Juan Manuel Zúñiga.png'),
  (80, 'Juan Sebastián Illera', 'CS', 4, 'Juan Sebastián Illera', 'Juan Sebastián Illera', 'laminas/Juan Sebastián Illera.png'),
  (81, 'Juan Sebastián Silva', 'Desarrollo', 1, 'Juan Sebastián Silva', 'Juan Sebastián Silva', 'laminas/Juan Sebastián Silva.png'),
  (82, 'Juliana Daza', 'Marketing', 2, 'Juliana Daza', 'Juliana Daza', 'laminas/Juliana Daza.png'),
  (83, 'Julieth Watson', 'Operaciones', 3, 'Julieth Watson', 'Julieth Watson', 'laminas/Julieth Watson.png'),
  (84, 'Karina Norambuena', 'Finanzas', 4, 'Karina Norambuena', 'Karina Norambuena', 'laminas/Karina Norambuena.png'),
  (85, 'Karol Rodríguez', 'Desarrollo', 1, 'Karol Rodríguez', 'Karol Rodríguez', 'laminas/Karol Rodríguez.png'),
  (86, 'Katherin Bustos', 'RRHH', 2, 'Katherin Bustos', 'Katherin Bustos', 'laminas/Katherin Bustos.png'),
  (87, 'Kathy Figueroa', 'Ventas', 3, 'Kathy Figueroa', 'Kathy Figueroa', 'laminas/Kathy Figueroa.png'),
  (88, 'Laura Hurtado', 'CS', 4, 'Laura Hurtado', 'Laura Hurtado', 'laminas/Laura Hurtado.png'),
  (89, 'Leonardo Revilla', 'Desarrollo', 1, 'Leonardo Revilla', 'Leonardo Revilla', 'laminas/Leonardo Revilla.png'),
  (90, 'Liliana Jiménez', 'Producto', 2, 'Liliana Jiménez', 'Liliana Jiménez', 'laminas/Liliana Jiménez.png'),
  (91, 'Liliana Martínez', 'Infraestructura', 3, 'Liliana Martínez', 'Liliana Martínez', 'laminas/Liliana Martínez.png'),
  (92, 'Lorena Silva', 'Diseño', 4, 'Lorena Silva', 'Lorena Silva', 'laminas/Lorena Silva.png'),
  (93, 'Luis Cova', 'Desarrollo', 1, 'Luis Cova', 'Luis Cova', 'laminas/Luis Cova.png'),
  (94, 'Luisa Aravena', 'CS', 2, 'Luisa Aravena', 'Luisa Aravena', 'laminas/Luisa Aravena.png'),
  (95, 'Maira Bello', 'Ventas', 3, 'Maira Bello', 'Maira Bello', 'laminas/Maira Bello.png'),
  (96, 'Manuel Hernández', 'Marketing', 4, 'Manuel Hernández', 'Manuel Hernández', 'laminas/Manuel Hernández.png'),
  (97, 'Manuel Lamas', 'CEO', 1, 'Manuel Lamas', 'Manuel Lamas', 'laminas/Manuel Lamas.png'),
  (98, 'Marcela Garzón', 'Producto', 2, 'Marcela Garzón', 'Marcela Garzón', 'laminas/Marcela Garzón.png'),
  (99, 'Marcos Butala', 'Desarrollo', 3, 'Marcos Butala', 'Marcos Butala', 'laminas/Marcos Butala.png'),
  (100, 'María Cecilia Calderini', 'CS', 4, 'María Cecilia Calderini', 'María Cecilia Calderini', 'laminas/María Cecilia Calderini.png'),
  (101, 'María de los Ángeles Pino', 'Desarrollo', 1, 'María de los Ángeles Pino', 'María de los Ángeles Pino', 'laminas/María de los Ángeles Pino.png'),
  (102, 'María Fernanda Díaz', 'Diseño', 2, 'María Fernanda Díaz', 'María Fernanda Díaz', 'laminas/María Fernanda Díaz.png'),
  (103, 'María José Maray', 'Ventas', 3, 'María José Maray', 'María José Maray', 'laminas/María José Maray.png'),
  (104, 'Marialy Torrealba', 'CS', 4, 'Marialy Torrealba', 'Marialy Torrealba', 'laminas/Marialy Torrealba.png'),
  (105, 'Mariela Cuahutencos', 'Desarrollo', 1, 'Mariela Cuahutencos', 'Mariela Cuahutencos', 'laminas/Mariela Cuahutencos.png'),
  (106, 'Mariom Soto', 'Marketing', 2, 'Mariom Soto', 'Mariom Soto', 'laminas/Mariom Soto.png'),
  (107, 'Marlén Arriagada', 'Operaciones', 3, 'Marlén Arriagada', 'Marlén Arriagada', 'laminas/Marlén Arriagada.png'),
  (108, 'Martín González', 'Finanzas', 4, 'Martín González', 'Martín González', 'laminas/Martín González.png'),
  (109, 'Martín Sztajn', 'Desarrollo', 1, 'Martín Sztajn', 'Martín Sztajn', 'laminas/Martín Sztajn.png'),
  (110, 'Matt Deacon', 'RRHH', 2, 'Matt Deacon', 'Matt Deacon', 'laminas/Matt Deacon.png'),
  (111, 'Mauricio Bustamante', 'Ventas', 3, 'Mauricio Bustamante', 'Mauricio Bustamante', 'laminas/Mauricio Bustamante.png'),
  (112, 'Melanie Galuschka', 'CS', 4, 'Melanie Galuschka', 'Melanie Galuschka', 'laminas/Melanie Galuschka.png'),
  (113, 'Melissa Calderón', 'Desarrollo', 1, 'Melissa Calderón', 'Melissa Calderón', 'laminas/Melissa Calderón.png'),
  (114, 'Mini Arévalo', 'Producto', 2, 'Mini Arévalo', 'Mini Arévalo', 'laminas/Mini Arévalo.png'),
  (115, 'Natali Rodríguez', 'Infraestructura', 3, 'Natali Rodríguez', 'Natali Rodríguez', 'laminas/Natali Rodríguez.png'),
  (116, 'Natalia Cancino', 'Diseño', 4, 'Natalia Cancino', 'Natalia Cancino', 'laminas/Natalia Cancino.png'),
  (117, 'Natalia Chandía', 'Desarrollo', 1, 'Natalia Chandía', 'Natalia Chandía', 'laminas/Natalia Chandía.png'),
  (118, 'Natalia Imazio', 'CS', 2, 'Natalia Imazio', 'Natalia Imazio', 'laminas/Natalia Imazio.png'),
  (119, 'Natalia Vidal', 'Ventas', 3, 'Natalia Vidal', 'Natalia Vidal', 'laminas/Natalia Vidal.png'),
  (120, 'Nataly Salinas', 'Marketing', 4, 'Nataly Salinas', 'Nataly Salinas', 'laminas/Nataly Salinas.png'),
  (121, 'Olga Torres', 'CEO', 1, 'Olga Torres', 'Olga Torres', 'laminas/Olga Torres.png'),
  (122, 'Orlando Vázquez', 'Producto', 2, 'Orlando Vázquez', 'Orlando Vázquez', 'laminas/Orlando Vázquez.png'),
  (123, 'Pablo Delillo', 'Desarrollo', 3, 'Pablo Delillo', 'Pablo Delillo', 'laminas/Pablo Delillo.png'),
  (124, 'Pablo Ormero', 'CS', 4, 'Pablo Ormero', 'Pablo Ormero', 'laminas/Pablo Ormero.png'),
  (125, 'Paola Melo', 'Desarrollo', 1, 'Paola Melo', 'Paola Melo', 'laminas/Paola Melo.png'),
  (126, 'Patricio Aliaga', 'Diseño', 2, 'Patricio Aliaga', 'Patricio Aliaga', 'laminas/Patricio Aliaga.png'),
  (127, 'Paula Pizarro', 'Ventas', 3, 'Paula Pizarro', 'Paula Pizarro', 'laminas/Paula Pizarro.png'),
  (128, 'Paulina Cáceres', 'CS', 4, 'Paulina Cáceres', 'Paulina Cáceres', 'laminas/Paulina Cáceres.png'),
  (129, 'Pilar Castillo', 'Desarrollo', 1, 'Pilar Castillo', 'Pilar Castillo', 'laminas/Pilar Castillo.png'),
  (130, 'Renzo Gola', 'Marketing', 2, 'Renzo Gola', 'Renzo Gola', 'laminas/Renzo Gola.png'),
  (131, 'Ricardo Vargas', 'Operaciones', 3, 'Ricardo Vargas', 'Ricardo Vargas', 'laminas/Ricardo Vargas.png'),
  (132, 'Robert Gutiérrez', 'Finanzas', 4, 'Robert Gutiérrez', 'Robert Gutiérrez', 'laminas/Robert Gutiérrez.png'),
  (133, 'Roberto Catalán', 'Desarrollo', 1, 'Roberto Catalán', 'Roberto Catalán', 'laminas/Roberto Catalán.png'),
  (134, 'Rodrigo Lerzundi', 'RRHH', 2, 'Rodrigo Lerzundi', 'Rodrigo Lerzundi', 'laminas/Rodrigo Lerzundi.png'),
  (135, 'Rodrigo Marambio', 'Ventas', 3, 'Rodrigo Marambio', 'Rodrigo Marambio', 'laminas/Rodrigo Marambio.png'),
  (136, 'Rodrigo Sepúlveda', 'CS', 4, 'Rodrigo Sepúlveda', 'Rodrigo Sepúlveda', 'laminas/Rodrigo Sepúlveda.png'),
  (137, 'Romina Lugo', 'Desarrollo', 1, 'Romina Lugo', 'Romina Lugo', 'laminas/Romina Lugo.png'),
  (138, 'Rubén Giraldo', 'Producto', 2, 'Rubén Giraldo', 'Rubén Giraldo', 'laminas/Rubén Giraldo.png'),
  (139, 'Santiago Saavedra', 'Infraestructura', 3, 'Santiago Saavedra', 'Santiago Saavedra', 'laminas/Santiago Saavedra.png'),
  (140, 'Saúl Ponce', 'Diseño', 4, 'Saúl Ponce', 'Saúl Ponce', 'laminas/Saúl Ponce.png'),
  (141, 'Sebastián Maureira', 'Desarrollo', 1, 'Sebastián Maureira', 'Sebastián Maureira', 'laminas/Sebastián Maureira.png'),
  (142, 'Sebastián Riquelme', 'CS', 2, 'Sebastián Riquelme', 'Sebastián Riquelme', 'laminas/Sebastián Riquelme.png'),
  (143, 'Sergio Carrasco', 'Ventas', 3, 'Sergio Carrasco', 'Sergio Carrasco', 'laminas/Sergio Carrasco.png'),
  (144, 'Steven Arias', 'Marketing', 4, 'Steven Arias', 'Steven Arias', 'laminas/Steven Arias.png'),
  (145, 'Sussane Henríquez', 'CEO', 1, 'Sussane Henríquez', 'Sussane Henríquez', 'laminas/Sussane Henríquez.png'),
  (146, 'Tatiana Torres', 'Producto', 2, 'Tatiana Torres', 'Tatiana Torres', 'laminas/Tatiana Torres.png'),
  (147, 'Valentín Marchant', 'Desarrollo', 3, 'Valentín Marchant', 'Valentín Marchant', 'laminas/Valentín Marchant.png'),
  (148, 'Valeska Rivera', 'CS', 4, 'Valeska Rivera', 'Valeska Rivera', 'laminas/Valeska Rivera.png'),
  (149, 'Víctor Bentiboglio', 'Desarrollo', 1, 'Víctor Bentiboglio', 'Víctor Bentiboglio', 'laminas/Víctor Bentiboglio.png'),
  (150, 'Víctor Gajardo', 'Diseño', 2, 'Víctor Gajardo', 'Víctor Gajardo', 'laminas/Víctor Gajardo.png'),
  (151, 'William Guzmán', 'Ventas', 3, 'William Guzmán', 'William Guzmán', 'laminas/William Guzmán.png'),
  (152, 'Wolfran Pinzón', 'CS', 4, 'Wolfran Pinzón', 'Wolfran Pinzón', 'laminas/Wolfran Pinzón.png'),
  (153, 'Yeferson Gómez', 'Desarrollo', 1, 'Yeferson Gómez', 'Yeferson Gómez', 'laminas/Yeferson Gómez.png')
on conflict (id) do update set
  name = excluded.name,
  role = excluded.role,
  pais_id = excluded.pais_id,
  login_name = excluded.login_name,
  login_password = excluded.login_password,
  lamina_path = excluded.lamina_path;

insert into public.figuritas (id, user_id, foto_path) values
  (1, 1, 'laminas/Abrahamzick Orozco.png'),
  (2, 2, 'laminas/Adrián Sepúlveda.png'),
  (3, 3, 'laminas/Adriana Celis.png'),
  (4, 4, 'laminas/Alberto Bachler.png'),
  (5, 5, 'laminas/Aldo Ayala.png'),
  (6, 6, 'laminas/Alejandro Albertz.png'),
  (7, 7, 'laminas/Alejandro González.png'),
  (8, 8, 'laminas/Alexis Bustamante.png'),
  (9, 9, 'laminas/Álvaro Bueno.png'),
  (10, 10, 'laminas/Andrés Ordoñez.png'),
  (11, 11, 'laminas/Andrés Osorio.png'),
  (12, 12, 'laminas/Andrés Quiero.png'),
  (13, 13, 'laminas/Andrés Tolosa.png'),
  (14, 14, 'laminas/Ángel Castillo.png'),
  (15, 15, 'laminas/Ángela Sierra.png'),
  (16, 16, 'laminas/Angie Callejas.png'),
  (17, 17, 'laminas/Ariadna Flores.png'),
  (18, 18, 'laminas/Ariel Gringaus.png'),
  (19, 19, 'laminas/Ariel Rojas.png'),
  (20, 20, 'laminas/Arnoldo Chazeau.png'),
  (21, 21, 'laminas/Arturo Rincón.png'),
  (22, 22, 'laminas/Ashly Flores.png'),
  (23, 23, 'laminas/Aymara Martínez.png'),
  (24, 24, 'laminas/Bastián Vallejos.png'),
  (25, 25, 'laminas/Belén Ávila.png'),
  (26, 26, 'laminas/Brenda Aquino.png'),
  (27, 27, 'laminas/Camila Casanova.png'),
  (28, 28, 'laminas/Carlos Rodríguez.png'),
  (29, 29, 'laminas/Carlos Vega.png'),
  (30, 30, 'laminas/Carolina Araya.png'),
  (31, 31, 'laminas/Catalina Fuentealba.png'),
  (32, 32, 'laminas/Catalina Mantilla.png'),
  (33, 33, 'laminas/Cesar Matheus.png'),
  (34, 34, 'laminas/Cristian Henríquez.png'),
  (35, 35, 'laminas/Cristian Noguera.png'),
  (36, 36, 'laminas/Cristian Zapata.png'),
  (37, 37, 'laminas/Cristina Molina.png'),
  (38, 38, 'laminas/Cynthia Marchant.png'),
  (39, 39, 'laminas/Daniel Medina.png'),
  (40, 40, 'laminas/Daniela Parra.png'),
  (41, 41, 'laminas/David Barreda.png'),
  (42, 42, 'laminas/David Guarín.png'),
  (43, 43, 'laminas/Derly Flórez.png'),
  (44, 44, 'laminas/Diana Sandoval.png'),
  (45, 45, 'laminas/Edward Henao.png'),
  (46, 46, 'laminas/Esteban Aguirre.png'),
  (47, 47, 'laminas/Evelyn Espejo.png'),
  (48, 48, 'laminas/Ezequiel Balasch.png'),
  (49, 49, 'laminas/Felipe Miranda.png'),
  (50, 50, 'laminas/Felipe Weiss.png'),
  (51, 51, 'laminas/Fernanda Florez.png'),
  (52, 52, 'laminas/Francisca Soto.png'),
  (53, 53, 'laminas/Gabriela Jugo.png'),
  (54, 54, 'laminas/Genito Andrade.png'),
  (55, 55, 'laminas/Gerardo Barragán.png'),
  (56, 56, 'laminas/Gonzalo Bertomeu.png'),
  (57, 57, 'laminas/Gonzalo de la Jara.png'),
  (58, 58, 'laminas/Gonzalo López.png'),
  (59, 59, 'laminas/Héctor Rojo.png'),
  (60, 60, 'laminas/Ignacio Portilla.png'),
  (61, 61, 'laminas/Israel Flores.png'),
  (62, 62, 'laminas/Jaime Herreros.png'),
  (63, 63, 'laminas/Javier Espinoza.png'),
  (64, 64, 'laminas/Javier Fonseca.png'),
  (65, 65, 'laminas/Javiera Huentemil.png'),
  (66, 66, 'laminas/Jeison Jiménez.png'),
  (67, 67, 'laminas/Jennifer Luengas.png'),
  (68, 68, 'laminas/Jesús Osorio.png'),
  (69, 69, 'laminas/Johan Casanova.png'),
  (70, 70, 'laminas/Johan Rosas.png'),
  (71, 71, 'laminas/Jonathan Sepúlveda.png'),
  (72, 72, 'laminas/Jorge Reynoso.png'),
  (73, 73, 'laminas/José Manuel Barros.png'),
  (74, 74, 'laminas/José Matus.png'),
  (75, 75, 'laminas/Jose Miguel Moreno.png'),
  (76, 76, 'laminas/José Romero.png'),
  (77, 77, 'laminas/Juan David Loaiza.png'),
  (78, 78, 'laminas/Juan Ignacio Castro.png'),
  (79, 79, 'laminas/Juan Manuel Zúñiga.png'),
  (80, 80, 'laminas/Juan Sebastián Illera.png'),
  (81, 81, 'laminas/Juan Sebastián Silva.png'),
  (82, 82, 'laminas/Juliana Daza.png'),
  (83, 83, 'laminas/Julieth Watson.png'),
  (84, 84, 'laminas/Karina Norambuena.png'),
  (85, 85, 'laminas/Karol Rodríguez.png'),
  (86, 86, 'laminas/Katherin Bustos.png'),
  (87, 87, 'laminas/Kathy Figueroa.png'),
  (88, 88, 'laminas/Laura Hurtado.png'),
  (89, 89, 'laminas/Leonardo Revilla.png'),
  (90, 90, 'laminas/Liliana Jiménez.png'),
  (91, 91, 'laminas/Liliana Martínez.png'),
  (92, 92, 'laminas/Lorena Silva.png'),
  (93, 93, 'laminas/Luis Cova.png'),
  (94, 94, 'laminas/Luisa Aravena.png'),
  (95, 95, 'laminas/Maira Bello.png'),
  (96, 96, 'laminas/Manuel Hernández.png'),
  (97, 97, 'laminas/Manuel Lamas.png'),
  (98, 98, 'laminas/Marcela Garzón.png'),
  (99, 99, 'laminas/Marcos Butala.png'),
  (100, 100, 'laminas/María Cecilia Calderini.png'),
  (101, 101, 'laminas/María de los Ángeles Pino.png'),
  (102, 102, 'laminas/María Fernanda Díaz.png'),
  (103, 103, 'laminas/María José Maray.png'),
  (104, 104, 'laminas/Marialy Torrealba.png'),
  (105, 105, 'laminas/Mariela Cuahutencos.png'),
  (106, 106, 'laminas/Mariom Soto.png'),
  (107, 107, 'laminas/Marlén Arriagada.png'),
  (108, 108, 'laminas/Martín González.png'),
  (109, 109, 'laminas/Martín Sztajn.png'),
  (110, 110, 'laminas/Matt Deacon.png'),
  (111, 111, 'laminas/Mauricio Bustamante.png'),
  (112, 112, 'laminas/Melanie Galuschka.png'),
  (113, 113, 'laminas/Melissa Calderón.png'),
  (114, 114, 'laminas/Mini Arévalo.png'),
  (115, 115, 'laminas/Natali Rodríguez.png'),
  (116, 116, 'laminas/Natalia Cancino.png'),
  (117, 117, 'laminas/Natalia Chandía.png'),
  (118, 118, 'laminas/Natalia Imazio.png'),
  (119, 119, 'laminas/Natalia Vidal.png'),
  (120, 120, 'laminas/Nataly Salinas.png'),
  (121, 121, 'laminas/Olga Torres.png'),
  (122, 122, 'laminas/Orlando Vázquez.png'),
  (123, 123, 'laminas/Pablo Delillo.png'),
  (124, 124, 'laminas/Pablo Ormero.png'),
  (125, 125, 'laminas/Paola Melo.png'),
  (126, 126, 'laminas/Patricio Aliaga.png'),
  (127, 127, 'laminas/Paula Pizarro.png'),
  (128, 128, 'laminas/Paulina Cáceres.png'),
  (129, 129, 'laminas/Pilar Castillo.png'),
  (130, 130, 'laminas/Renzo Gola.png'),
  (131, 131, 'laminas/Ricardo Vargas.png'),
  (132, 132, 'laminas/Robert Gutiérrez.png'),
  (133, 133, 'laminas/Roberto Catalán.png'),
  (134, 134, 'laminas/Rodrigo Lerzundi.png'),
  (135, 135, 'laminas/Rodrigo Marambio.png'),
  (136, 136, 'laminas/Rodrigo Sepúlveda.png'),
  (137, 137, 'laminas/Romina Lugo.png'),
  (138, 138, 'laminas/Rubén Giraldo.png'),
  (139, 139, 'laminas/Santiago Saavedra.png'),
  (140, 140, 'laminas/Saúl Ponce.png'),
  (141, 141, 'laminas/Sebastián Maureira.png'),
  (142, 142, 'laminas/Sebastián Riquelme.png'),
  (143, 143, 'laminas/Sergio Carrasco.png'),
  (144, 144, 'laminas/Steven Arias.png'),
  (145, 145, 'laminas/Sussane Henríquez.png'),
  (146, 146, 'laminas/Tatiana Torres.png'),
  (147, 147, 'laminas/Valentín Marchant.png'),
  (148, 148, 'laminas/Valeska Rivera.png'),
  (149, 149, 'laminas/Víctor Bentiboglio.png'),
  (150, 150, 'laminas/Víctor Gajardo.png'),
  (151, 151, 'laminas/William Guzmán.png'),
  (152, 152, 'laminas/Wolfran Pinzón.png'),
  (153, 153, 'laminas/Yeferson Gómez.png')
on conflict (id) do update set
  user_id = excluded.user_id,
  foto_path = excluded.foto_path;

